typeof khJQuery==="undefined"&&(khJQuery=jQuery);
(function(a){a.fn.fakeLoader=function(e){var b=a.extend({timeToHide:1200,pos:"fixed",top:"0px",left:"0px",width:"40px",height:"40px",zIndex:"999",bgColor:"#2ecc71"},e),c=a(this);c.css({position:b.pos,width:b.width,height:b.height,top:b.top,left:b.left});c.each(function(){c.html('<div class="cu_spinner1"><div class="cu_double-bounce1"></div><div class="cu_double-bounce2"></div></div>')});a.fn.fakeLoader.centerLoader=function(){var c=a(".cu_spinner1"),d=a(b.centerContainer),e=d.width(),d=d.height(),
f=c.outerWidth(),g=c.outerHeight();c.css({position:"absolute",left:e/2-f/2,top:d/2-g/2})};b.timeToHide&&setTimeout(function(){a(c).fadeOut()},b.timeToHide);a(window).load(function(){a.fn.fakeLoader.centerLoader();a(window).resize(function(){a.fn.fakeLoader.centerLoader()})});return this.css({backgroundColor:b.bgColor,zIndex:b.zIndex})}})(khJQuery);

(function(c){c.cusearch=function(g,f){function i(a){c.data(c("#"+d.settings.initiator)[0],d.settings.initiator)[d.settings.action](a,"stage1")}function j(a){c.data(c("#"+d.settings.initiator)[0],d.settings.initiator)[d.settings.action](a,"twitter")}function k(a){c.data(c("#"+d.settings.initiator)[0],d.settings.initiator)[d.settings.action](a,"images")}function h(a,b,c){console.log("textStatus= "+b+"\nerrorThrown= "+c)}var d=this;d.settings={};c(g);d.settings=c.extend({},{name:"cusearch",version:"2.3.0.315"},
f);d.search=function(a){var b,e;e=c.data(c("#"+d.settings.initiator)[0],d.settings.initiator);if(a.query){if(!d.settings.mi)d.settings.mi=e.localStorage("cu_mi")||e.getCookie("kh_uid")||"";b=a.hostname?a.hostname:d.settings.hostname;e=e.encodePlus(a.query);b="//"+b+"/lookup?q="+e;b+=a.fc?"&fc="+a.fc:"&fc=-1";b+=a.ext?"&sw=ext&ext=true":"&sw=popup";b+=a.v?"&srcver="+a.v:"";b+=a.pid?"&pid="+a.pid:"";b+=a.openMethod?"&om="+a.openMethod:"";b+=a.ua!="lc"?a.lang!==void 0&&a.lang.length===2?"&lang="+a.lang:
"":a.lang?"&lang="+a.lang:"";b+=a.trending?"&trending="+a.trending:"";b+=a.ab?"&ab="+a.ab:"";b+=a.ua?"&ua="+a.ua:a.tp?"&ua=tp":"";b+=a.tp?"&tp="+a.tp:"";b+=a.cardWidth?"&cardwidth="+a.cardWidth:"";b+=d.settings.mi?"&mi="+d.settings.mi:"";b+=a.xparms?a.xparms:"";b+="&cards=1";e=a.referrer||(window.location!=window.parent.location?document.referrer:location.href);b+="&ref="+encodeURIComponent(e);b+=a.callbackParam?a.callbackParam:"&callback=?";a.imageLater?c.ajax({url:b+"&lookup=news_web_images",dataType:"json",
success:k,error:h}):(c.ajax({url:b+"&lookup=stage1",dataType:"json",success:i,error:h}),c.ajax({url:b+"&lookup=twitter",dataType:"json",success:j,error:h}))}}};c.fn.cusearch=function(g){return this.each(function(){var f;void 0==c.data(this,"cusearch")?(f=new c.cusearch(this,g),c.data(this,"cusearch",f)):c.data(this,"cusearch")})}})(khJQuery,window,document);

(function(d,r,s,h){d.cufayt=function(f,j){function o(b){var a=!0;switch(b){case 9:case 13:case 27:case 33:case 34:case 35:case 36:case 37:case 38:case 39:case 40:case 45:a=!1}return a}function m(b,a){var c=-1,e="";if(b.constructor==String&&(c=b.indexOf("("),c>-1)){b=b.substring(c+1,b.length-1);try{b=d.parseJSON(b)}catch(g){console.log("error json fayt parsing")}}if(b!==h&&b[1]!==h){i[b[0]]=[b[0],b[1]];i.length+=1;for(c=0;c<b[1].length;c++)e+='<div><a href="">'+b[1][c]+"</a></div>";if(typeof a==="undefined"||
a.constructor===String)a=d(this);a.html(e).css("visibility","visible").css("z-index",400).show()}}function n(b){c.unHighlight();var a=b.suggest.pos;a!==-1?(d("#cufayt").find("div:eq("+a+")").addClass("hover"),d("#cusearch").val(d("#cufayt").find("div:eq("+a+")").text())):d("#cusearch").val(b.suggest.typed)}function q(b,a,c){console.log("textStatus= "+a+"\nerrorThrown= "+c)}var c=this;c.settings={};d(f);var k=0,i={length:0},l,g;c.settings=d.extend({},{version:"2.3.0.315",name:"cufayt"},j);l=d("#"+
c.settings.initiator);c.faytKey=function(b){var a=b.data;if(!a)a=c.settings;var p="https://"+(a.lang!==h&&a.lang.length===2?a.lang:"en")+".wikipedia.org/w/api.php?action=opensearch&limit=6&search=",e=a.suggest.pos,f=d("#cufayt");if(o(b.keyCode))a.suggest.typed=d("#cusearch").val(),a.suggest.pos=-1,k===0&&(k=setTimeout(function(){k=0;var b="",b=d("#cusearch").val();a.suggest.typed=b;b.length<1?c.hideSuggest(null,a):i[b]?m(i[b],f):(b=p+encodeURIComponent(b)+"&callback=?",d.ajax({url:b,dataType:"json",
context:f,success:m,error:q}))},200));else if(b.keyCode==40)e<i[a.suggest.typed][1].length-1?e++:e=-1,a.suggest.pos=e,n(a);else if(b.keyCode==38)b.preventDefault(),b.stopImmediatePropagation(),e>0?e--:e=-1,a.suggest.pos=e,n(a);else if(b.keyCode==13)return b.preventDefault(),b.stopImmediatePropagation(),a.query=d(this).val(),a.fc=-1,a.ua="sbr",a.lang=a.lang?a.lang:"en",a.openMethod=c.settings.openMethod?c.settings.openMethod:"",a.tp==="true"?(b=c.encodePlus(a.query),e=a.pid&&a.pid!=="GenericVersion"?
"&pid="+a.pid:"",e+=a.openMethod?"&om="+a.openMethod:"",e=e.replace("&","?"),d("#cufayt.faythp").length>0?location.href="//"+c.settings.hostname+"/"+a.lang+"/topic/"+b+e:parent.postMessage&&parent.postMessage("cu_change_url://"+c.settings.hostname+"/"+a.lang+"/topic/"+b+e,"*")):(g||(g=d.data(l[0],c.settings.initiator)),c.hideSuggest(null,a),g[c.settings.action](a)),!1;else b.keyCode==27&&c.hideSuggest(null,a)};c.mouseHighlight=function(b){c.unHighlight();b.data.suggest.pos=d(this).index();d(this).addClass("hover")};
c.unHighlight=function(){d("#cufayt .hover").removeClass("hover")};c.hideSuggest=function(b){var a;if(b)a=b.data;if(!a)a=c.settings;if(a){if(a.suggest)a.suggest.pos=-1,a.suggest.typed="";setTimeout(function(){d("#cufayt").hide()},400)}};c.encodePlus=function(b){return encodeURIComponent(b.replace(/%/g,"%25").replace(/\+/g,"%2B").replace(/\?/g,"%3F")).replace(/\'/g,"%27").replace(/\"/g,"%22")};c.handleFayt=function(b){b.preventDefault();var a=b.data;if(!a)a=c.settings;var f=a.lang!=h&&a.lang.length===
2?a.lang:"en";a.query=b.data&&b.data.query?b.data.query:d(this).text();a.fc=-1;a.ua="fayt";a.fo=!0;a.openMethod=c.settings.openMethod?c.settings.openMethod:"";b=(a.pid&&a.pid!=="GenericVersion"?"&pid="+a.pid:"")+(a.openMethod?"&om="+a.openMethod:"");a.tp==="true"?(a=c.encodePlus(a.query),location.href.indexOf("nopos=true")>-1&&(b+="&nopos=true"),b=b.replace("&","?"),d("#cufayt.faythp").length>0?location.href="//"+c.settings.hostname+"/"+f+"/topic/"+a+b:parent.postMessage&&parent.postMessage("cu_change_url://"+
c.settings.hostname+"/"+f+"/topic/"+a+b,"*")):(g||(g=d.data(l[0],c.settings.initiator)),c.hideSuggest(null,a),g[c.settings.action](a));return!1}};d.fn.cufayt=function(f){return this.each(function(){if(h==d(this).data("cufayt")){var j=new d.cufayt(this,f);d(this).data("cufayt",j)}else d.data(this,"cufayt")})}})(khJQuery,window,document);

